export const fortunes: Record<string, string[]> = {
  Rat: [
    "Your quick-witted nature will lead you to discover a hidden gem in the crypto market this week.",
    "Your adaptability will be your greatest asset as you navigate market volatility with ease.",
    "Your resourcefulness will help you find unique opportunities that others miss in the DeFi space.",
    "Your charm will open doors to valuable networking opportunities in the crypto community.",
    "Trust your intuition this week—it will guide you to a promising new project before it goes mainstream.",
  ],
  Ox: [
    "Your persistence will pay off as a long-term investment finally shows promising returns.",
    "Your methodical approach to research will help you avoid common pitfalls in the market.",
    "Your patience is your superpower—hold steady through market fluctuations for optimal results.",
    "Your diligence in due diligence will protect your portfolio from unnecessary risks.",
    "Your steady hand will guide you through market turbulence to find stability and growth.",
  ],
  Tiger: [
    "Your bold approach will lead you to discover an innovative project with massive potential.",
    "Your competitive spirit will drive you to outperform the market through strategic moves.",
    "Your courage to take calculated risks will open doors to exceptional opportunities.",
    "Your natural leadership will attract like-minded individuals to collaborate on a promising venture.",
    "Your enthusiasm will energize your investment strategy, bringing renewed focus and clarity.",
  ],
  Rabbit: [
    "Your cautious approach will help you avoid a common pitfall that affects many investors this week.",
    "Your diplomatic skills will help you navigate a complex negotiation in your favor.",
    "Your attention to detail will reveal a subtle market trend that others have overlooked.",
    "Your intuitive understanding of value will guide you to a project with long-term potential.",
    "Your balanced perspective will help you make level-headed decisions during market excitement.",
  ],
  Dragon: [
    "Your natural confidence will attract powerful allies in the crypto space this week.",
    "Your visionary thinking will help you spot a trend before it becomes mainstream.",
    "Your ambitious nature will drive you to explore innovative projects with high growth potential.",
    "Your charismatic energy will open doors to exclusive opportunities in the crypto community.",
    "Your bold decisions will set you apart from the crowd, leading to exceptional results.",
  ],
  Snake: [
    "Your wisdom will guide you to see beyond the hype and identify true value in the market.",
    "Your analytical mind will uncover a hidden pattern in market movements that others miss.",
    "Your intuitive nature will help you time your moves perfectly for optimal results.",
    "Your patient approach will pay dividends as you wait for the perfect entry point.",
    "Your strategic thinking will help you navigate complex DeFi protocols with ease.",
  ],
  Horse: [
    "Your energetic approach will help you stay ahead of fast-moving market trends.",
    "Your independent thinking will lead you to discover an overlooked gem in the crypto space.",
    "Your natural enthusiasm will attract opportunities for collaboration with innovative projects.",
    "Your adaptability will be your greatest asset as you navigate changing market conditions.",
    "Your quick reflexes will help you capitalize on a fleeting opportunity for significant gains.",
  ],
  Goat: [
    "Your creative thinking will help you find unique solutions to common investment challenges.",
    "Your gentle persistence will lead to steady growth in your crypto portfolio.",
    "Your artistic perspective will help you appreciate the aesthetic value of NFT projects.",
    "Your compassionate approach to community will connect you with supportive networks.",
    "Your imaginative nature will help you envision the future potential of emerging technologies.",
  ],
  Monkey: [
    "Your clever approach will help you find innovative ways to maximize your returns.",
    "Your curiosity will lead you to discover a promising project in its early stages.",
    "Your versatility will allow you to thrive across different sectors of the crypto ecosystem.",
    "Your quick thinking will help you navigate market volatility with confidence and skill.",
    "Your playful experimentation will lead to unexpected but valuable discoveries in DeFi.",
  ],
  Rooster: [
    "Your attention to detail will help you spot a critical opportunity that others overlook.",
    "Your practical approach will ground your investment strategy in solid fundamentals.",
    "Your observant nature will alert you to important market shifts before they become obvious.",
    "Your honest assessment of projects will help you avoid hype-driven investments.",
    "Your precision in timing will help you optimize your entry and exit points.",
  ],
  Dog: [
    "Your loyalty to your investment principles will serve you well during market uncertainty.",
    "Your protective instincts will help you safeguard your assets through proper security measures.",
    "Your honest approach will attract trustworthy partners for potential collaborations.",
    "Your sense of justice will guide you toward projects with ethical foundations and practices.",
    "Your reliable nature will make you a valued member of any crypto community you join.",
  ],
  Pig: [
    "Your generous spirit will open doors to collaborative opportunities with promising returns.",
    "Your optimistic outlook will help you see potential where others see obstacles.",
    "Your honest approach will attract trustworthy partners and advisors in the crypto space.",
    "Your diligent research will lead you to discover a project with strong fundamentals.",
    "Your kind nature will connect you with supportive communities that share valuable insights.",
  ],
  default: [
    "The stars align for a prosperous week in your crypto journey.",
    "Your intuition will guide you to make wise choices in volatile markets.",
    "A surprising opportunity will present itself—stay alert and ready to act.",
    "Your patience with long-term investments will be rewarded soon.",
    "Your unique perspective will help you spot value where others don't look.",
  ],
}
