export const zodiacData = {
  western: {
    id: "western",
    name: "Western Zodiac",
    description: "Based on the Sun's position at your birth",
    requirements: "Date of birth (day, month, year)",
    image: "/images/western-zodiac.png",
    emoji: "🌟",
    signs: [
      { name: "Aries", dates: "March 21 - April 19", element: "Fire", symbol: "♈" },
      { name: "Taurus", dates: "April 20 - May 20", element: "Earth", symbol: "♉" },
      { name: "Gemini", dates: "May 21 - June 20", element: "Air", symbol: "♊" },
      { name: "Cancer", dates: "June 21 - July 22", element: "Water", symbol: "♋" },
      { name: "Leo", dates: "July 23 - August 22", element: "Fire", symbol: "♌" },
      { name: "Virgo", dates: "August 23 - September 22", element: "Earth", symbol: "♍" },
      { name: "Libra", dates: "September 23 - October 22", element: "Air", symbol: "♎" },
      { name: "Scorpio", dates: "October 23 - November 21", element: "Water", symbol: "♏" },
      { name: "Sagittarius", dates: "November 22 - December 21", element: "Fire", symbol: "♐" },
      { name: "Capricorn", dates: "December 22 - January 19", element: "Earth", symbol: "♑" },
      { name: "Aquarius", dates: "January 20 - February 18", element: "Air", symbol: "♒" },
      { name: "Pisces", dates: "February 19 - March 20", element: "Water", symbol: "♓" },
    ],
  },
  chinese: {
    id: "chinese",
    name: "Chinese Zodiac",
    description: "Based on 12-year animal cycle in the lunar calendar",
    requirements: "Year of birth",
    image: "/images/chinese-zodiac.png",
    emoji: "🐉",
    signs: [
      { name: "Rat", years: [1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020], element: "Water", emoji: "🐀" },
      { name: "Ox", years: [1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021], element: "Earth", emoji: "🐂" },
      { name: "Tiger", years: [1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022], element: "Wood", emoji: "🐅" },
      { name: "Rabbit", years: [1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023], element: "Wood", emoji: "🐇" },
      { name: "Dragon", years: [1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024], element: "Earth", emoji: "🐉" },
      { name: "Snake", years: [1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025], element: "Fire", emoji: "🐍" },
      { name: "Horse", years: [1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026], element: "Fire", emoji: "🐎" },
      { name: "Goat", years: [1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027], element: "Earth", emoji: "🐐" },
      { name: "Monkey", years: [1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028], element: "Metal", emoji: "🐒" },
      { name: "Rooster", years: [1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029], element: "Metal", emoji: "🐓" },
      { name: "Dog", years: [1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030], element: "Earth", emoji: "🐕" },
      { name: "Pig", years: [1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031], element: "Water", emoji: "🐖" },
    ],
  },
  vedic: {
    id: "vedic",
    name: "Vedic Zodiac",
    description: "Based on actual constellations (sidereal zodiac)",
    requirements: "Date of birth (day, month, year)",
    image: "/images/vedic-zodiac.png",
    emoji: "🕉",
    signs: [
      { name: "Mesha (Aries)", dates: "April 14 - May 14", element: "Fire", symbol: "♈" },
      { name: "Vrishabha (Taurus)", dates: "May 15 - June 14", element: "Earth", symbol: "♉" },
      { name: "Mithuna (Gemini)", dates: "June 15 - July 14", element: "Air", symbol: "♊" },
      { name: "Karka (Cancer)", dates: "July 15 - August 14", element: "Water", symbol: "♋" },
      { name: "Simha (Leo)", dates: "August 15 - September 15", element: "Fire", symbol: "♌" },
      { name: "Kanya (Virgo)", dates: "September 16 - October 15", element: "Earth", symbol: "♍" },
      { name: "Tula (Libra)", dates: "October 16 - November 14", element: "Air", symbol: "♎" },
      { name: "Vrishchika (Scorpio)", dates: "November 15 - December 14", element: "Water", symbol: "♏" },
      { name: "Dhanu (Sagittarius)", dates: "December 15 - January 13", element: "Fire", symbol: "♐" },
      { name: "Makara (Capricorn)", dates: "January 14 - February 12", element: "Earth", symbol: "♑" },
      { name: "Kumbha (Aquarius)", dates: "February 13 - March 14", element: "Air", symbol: "♒" },
      { name: "Meena (Pisces)", dates: "March 15 - April 13", element: "Water", symbol: "♓" },
    ],
  },
  mayan: {
    id: "mayan",
    name: "Mayan Zodiac",
    description: "Based on Tzolk'in calendar (260-day cycle)",
    requirements: "Date of birth (day, month, year)",
    image: "/images/mayan-zodiac.png",
    emoji: "🌿",
    signs: [
      { name: "Imix (Crocodile)", dates: "Day 1", element: "Earth", symbol: "🐊" },
      { name: "Ik (Wind)", dates: "Day 2", element: "Air", symbol: "💨" },
      { name: "Akbal (Night)", dates: "Day 3", element: "Water", symbol: "🌙" },
      { name: "Kan (Seed)", dates: "Day 4", element: "Earth", symbol: "🌱" },
      { name: "Chicchan (Serpent)", dates: "Day 5", element: "Fire", symbol: "🐍" },
      { name: "Cimi (Death)", dates: "Day 6", element: "Air", symbol: "💀" },
      { name: "Manik (Deer)", dates: "Day 7", element: "Water", symbol: "🦌" },
      { name: "Lamat (Star)", dates: "Day 8", element: "Earth", symbol: "⭐" },
      { name: "Muluc (Water)", dates: "Day 9", element: "Water", symbol: "💧" },
      { name: "Oc (Dog)", dates: "Day 10", element: "Fire", symbol: "🐕" },
      { name: "Chuen (Monkey)", dates: "Day 11", element: "Air", symbol: "🐒" },
      { name: "Eb (Road)", dates: "Day 12", element: "Earth", symbol: "🛣️" },
      { name: "Ben (Reed)", dates: "Day 13", element: "Water", symbol: "🌾" },
      { name: "Ix (Jaguar)", dates: "Day 14", element: "Fire", symbol: "🐆" },
      { name: "Men (Eagle)", dates: "Day 15", element: "Air", symbol: "🦅" },
      { name: "Cib (Wisdom)", dates: "Day 16", element: "Earth", symbol: "🧠" },
      { name: "Caban (Earth)", dates: "Day 17", element: "Earth", symbol: "🌎" },
      { name: "Etznab (Flint)", dates: "Day 18", element: "Fire", symbol: "🔪" },
      { name: "Cauac (Storm)", dates: "Day 19", element: "Water", symbol: "⛈️" },
      { name: "Ahau (Sun)", dates: "Day 20", element: "Fire", symbol: "☀️" },
    ],
  },
}
