"use client"

import type React from "react"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { zodiac } from "@/lib/zodiac"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Sparkles } from "lucide-react"

export function ZodiacForm() {
  const router = useRouter()
  const [username, setUsername] = useState("")
  const [birthYear, setBirthYear] = useState("")
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState("")

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError("")

    if (!username || !birthYear) {
      setError("Please fill in all fields")
      return
    }

    const year = Number.parseInt(birthYear)
    if (isNaN(year) || year < 1900 || year > new Date().getFullYear()) {
      setError("Please enter a valid birth year")
      return
    }

    setIsLoading(true)
    try {
      const sign = zodiac.getSign(year)
      const params = new URLSearchParams({
        username,
        year: birthYear,
        sign: sign.name,
      })

      router.push(`/fortune?${params.toString()}`)
    } catch (err) {
      setError("Something went wrong. Please try again.")
      setIsLoading(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="space-y-2">
        <Label htmlFor="username" className="text-white">
          Farcaster Username
        </Label>
        <Input
          id="username"
          placeholder="@username"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          className="bg-white/20 border-violet-300/30 text-white placeholder:text-violet-200/50"
        />
        <p className="text-xs text-violet-300">Enter your Farcaster username without the @ symbol</p>
      </div>

      <div className="space-y-2">
        <Label htmlFor="birthYear" className="text-white">
          Birth Year
        </Label>
        <Input
          id="birthYear"
          placeholder="YYYY"
          value={birthYear}
          onChange={(e) => setBirthYear(e.target.value)}
          className="bg-white/20 border-violet-300/30 text-white placeholder:text-violet-200/50"
        />
        <p className="text-xs text-violet-300">Your Chinese zodiac sign will be determined by your birth year</p>
      </div>

      {error && <p className="text-red-300 text-sm">{error}</p>}

      <Button type="submit" className="w-full bg-violet-600 hover:bg-violet-700" disabled={isLoading}>
        <Sparkles className="mr-2 h-4 w-4" />
        {isLoading ? "Consulting the stars..." : "Reveal My Fortune"}
      </Button>

      <p className="text-xs text-center text-violet-300">
        Your fortune will be uniquely generated by AI based on your Chinese zodiac sign
      </p>
    </form>
  )
}
